# ????
research:
  name: ????????
  version: 1.0.0

# ?????
server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8

# Spring??
spring:
  profiles:
    active: dev
  application:
    name: research-management
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/research_management?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456


  # ??????
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  data:
    # Redis??
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 0

# MyBatis-Plus??
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.university.research.**.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT??
jwt:
  secret: researchManagementSecretKey2024
  expiration: 86400000  # 24??

# ????
logging:
  level:
    com.university.research: debug
    org.springframework.security: debug

# Knife4j??
knife4j:
  enable: true
  setting:
    language: zh_cn